# Generated by Django 5.2.6 on 2025-09-09 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Granja',
            fields=[
                ('id_granja', models.AutoField(primary_key=True, serialize=False)),
                ('nome_granja', models.CharField(max_length=255)),
                ('cnpj_granja', models.CharField(max_length=255)),
                ('cidade_granja', models.CharField(max_length=255)),
                ('uf_granja', models.CharField(max_length=255)),
                ('ativo_granja', models.BooleanField(default=True)),
                ('cria_em_grnaj', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galpao',
            fields=[
                ('id_galpao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_galpao', models.CharField(max_length=255)),
                ('codigo_galpao', models.CharField(max_length=255)),
                ('cap_galpao', models.IntegerField(default=0)),
                ('area_galpao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_galpao', models.CharField(max_length=255)),
                ('ativo_galpao', models.BooleanField(default=True)),
                ('cria_em_galpao', models.DateTimeField(auto_now_add=True)),
                ('id_granja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumixapp.granja')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('nome_lote', models.CharField(max_length=255)),
                ('codigo_lote', models.CharField(max_length=255)),
                ('linhagem_lote', models.CharField(max_length=255)),
                ('d_entrada_lote', models.DateField()),
                ('d_saida_lote', models.DateField()),
                ('mot_saida_lote', models.CharField(max_length=255)),
                ('cria_em_lote', models.DateTimeField(auto_now_add=True)),
                ('id_galpao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumixapp.galpao')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.CharField(max_length=255)),
                ('descricao_evento', models.CharField(max_length=255)),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumixapp.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id_ambiente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_leitura_ambiente', models.CharField(max_length=255)),
                ('lido_em_ambiente', models.DateTimeField(auto_now_add=True)),
                ('temp_c_ambiente', models.DecimalField(decimal_places=2, max_digits=5)),
                ('co2_ambiente', models.IntegerField(default=0)),
                ('nh3_ambiente', models.IntegerField(default=0)),
                ('vel_ar_ambiente', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sensor_ambiente', models.CharField(max_length=255)),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumixapp.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('data_alerta', models.DateTimeField(auto_now_add=True)),
                ('severidade_alerta', models.CharField(max_length=255)),
                ('categoria_alerta', models.CharField(max_length=255)),
                ('msg_alerta', models.CharField(max_length=255)),
                ('resolvido_alerta', models.BooleanField(default=True)),
                ('resolvido_em_alerta', models.DateTimeField(auto_now_add=True)),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumixapp.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id_agua', models.AutoField(primary_key=True, serialize=False)),
                ('data_agua', models.DateField()),
                ('litro_agua', models.DecimalField(decimal_places=2, max_digits=12)),
                ('obs_agua', models.CharField(max_length=255)),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumixapp.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Mortalidade',
            fields=[
                ('id_mortalidade', models.AutoField(primary_key=True, serialize=False)),
                ('data_mortalidade', models.DateField()),
                ('qtd_mortalidade', models.IntegerField(default=0)),
                ('causa_mortalidade', models.CharField(max_length=255)),
                ('obs_mortalidade', models.CharField(max_length=255)),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumixapp.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id_pesagem', models.AutoField(primary_key=True, serialize=False)),
                ('data_pesagem', models.DateField()),
                ('amostra_pesagem', models.IntegerField(default=0)),
                ('pmedio_pesagem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cva_pesagem', models.DecimalField(decimal_places=3, max_digits=6)),
                ('obs_pesagem', models.CharField(max_length=255)),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumixapp.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Racao',
            fields=[
                ('id_racao', models.AutoField(primary_key=True, serialize=False)),
                ('data_racao', models.DateField()),
                ('kg_racao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fase_racao', models.CharField(max_length=255)),
                ('obs_racao', models.CharField(max_length=255)),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumixapp.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id_tratamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_in_tratamento', models.DateField()),
                ('data_fim_tratamento', models.DateField()),
                ('produto_tratamento', models.CharField(max_length=255)),
                ('p_ativo_tratamento', models.CharField(max_length=255)),
                ('via_tratamento', models.CharField(max_length=255)),
                ('dose_tratamento', models.CharField(max_length=255)),
                ('motivo_tratamento', models.CharField(max_length=255)),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumixapp.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id_vacinacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_vacinacao', models.DateField()),
                ('vacina_vacinacao', models.CharField(max_length=255)),
                ('via_vacinacao', models.CharField(max_length=255)),
                ('obs_vacinacao', models.CharField(max_length=255)),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumixapp.lote')),
            ],
        ),
    ]
